#!/usr/bin/env bash
# Build an MCPB bundle for arxiv-mcp-server.
# Outputs: mcpb-build/arxiv-mcp-server-darwin-<arch>-<version>.mcpb
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PYTHON_BIN="${PYTHON:-python3}"
BUILD_DIR="$ROOT/mcpb-build"

"$PYTHON_BIN" - <<'PYEOF'
import sys
if sys.implementation.name != "cpython" or sys.version_info[:2] != (3, 11):
    raise SystemExit(
        "CPython 3.11.x is required to build the MCPB bundle because its "
        f"vendored native dependencies target that ABI; got "
        f"{sys.implementation.name} {sys.version.split()[0]}"
    )
if sys.platform != "darwin":
    raise SystemExit(
        "macOS is required to build this MCPB bundle because its output is "
        f"labeled for Darwin; got {sys.platform}"
    )
PYEOF

VERSION="$($PYTHON_BIN - "$ROOT/pyproject.toml" <<'PYEOF'
import pathlib, re, sys
text = pathlib.Path(sys.argv[1]).read_text()
match = re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
if not match:
    raise SystemExit('Could not find project version in pyproject.toml')
print(match.group(1))
PYEOF
)"

echo "Building arxiv-mcp-server v$VERSION MCPB bundle..."

# Clean and create structure
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR/server/vendor"

# Generate a 512x512 teal icon (pure Python, no deps)
"$PYTHON_BIN" - "$BUILD_DIR/icon.png" <<'PYEOF'
import struct, zlib, sys

def make_png(width, height, r, g, b):
    def chunk(name, data):
        c = name + data
        return struct.pack('>I', len(data)) + c + struct.pack('>I', zlib.crc32(c) & 0xFFFFFFFF)
    scanline = b'\x00' + bytes([r, g, b] * width)
    return (
        b'\x89PNG\r\n\x1a\n'
        + chunk(b'IHDR', struct.pack('>IIBBBBB', width, height, 8, 2, 0, 0, 0))
        + chunk(b'IDAT', zlib.compress(scanline * height))
        + chunk(b'IEND', b'')
    )

with open(sys.argv[1], 'wb') as f:
    f.write(make_png(512, 512, 20, 108, 148))
print("Generated icon.png")
PYEOF

# Copy manifest and stamp version
"$PYTHON_BIN" - "$ROOT/manifest.json" "$BUILD_DIR/manifest.json" "$VERSION" <<'PYEOF'
import json, sys
with open(sys.argv[1]) as f:
    manifest = json.load(f)
manifest['version'] = sys.argv[3]
with open(sys.argv[2], 'w') as f:
    json.dump(manifest, f, indent=2)
    f.write('\n')
print(f"Stamped manifest version: {sys.argv[3]}")
PYEOF

# Copy server source
cp -R "$ROOT/src/arxiv_mcp_server" "$BUILD_DIR/server/arxiv_mcp_server"
echo "Copied server source"

# Vendor the locked base and PDF-extra dependencies. Exporting from uv.lock keeps
# the bundle aligned with the package release instead of maintaining a second
# handwritten dependency set.
echo "Vendoring locked dependencies..."
REQUIREMENTS_FILE="$BUILD_DIR/mcpb-requirements.txt"
uv export \
  --quiet \
  --locked \
  --no-dev \
  --extra pdf \
  --no-emit-project \
  --format requirements-txt \
  --output-file "$REQUIREMENTS_FILE"
"$PYTHON_BIN" -m pip install \
  --target "$BUILD_DIR/server/vendor" \
  --no-user \
  --quiet \
  --requirement "$REQUIREMENTS_FILE"
rm -f "$REQUIREMENTS_FILE"
echo "Dependencies vendored"

# Avoid shipping generated bytecode from local source copies or import-time validation.
find "$BUILD_DIR" -type d -name __pycache__ -prune -exec rm -rf {} +
find "$BUILD_DIR" -type f \( -name '*.pyc' -o -name '*.pyo' \) -delete

# Pack with mcpb
if ! command -v npx >/dev/null 2>&1; then
  echo "ERROR: npx is required to run @anthropic-ai/mcpb" >&2
  exit 1
fi

echo "Packing..."
cd "$BUILD_DIR"
npx --yes @anthropic-ai/mcpb@2.1.2 pack

ARTIFACT=$(find "$BUILD_DIR" -maxdepth 1 -name '*.mcpb' -print -quit)
if [[ -z "$ARTIFACT" ]]; then
  echo "ERROR: no .mcpb file found after packing" >&2
  exit 1
fi

ARCH="$(uname -m)"
FINAL_ARTIFACT="$BUILD_DIR/arxiv-mcp-server-darwin-$ARCH-$VERSION.mcpb"
if [[ "$ARTIFACT" != "$FINAL_ARTIFACT" ]]; then
  mv "$ARTIFACT" "$FINAL_ARTIFACT"
fi

echo "Built: $FINAL_ARTIFACT"
